dist: trusty
language: php

git:
  depth: 1

php:
- 7.2

branches:
  only:
    master

addons:
  sonarcloud:
    organization: "bleuenn-github"
      token:
        secure: $s2ima

script:
- cd model
- phpunit DAOTest.php
- cd ..
- sonar-scanner \
  -Dsonar.projectKey=Bleuenn_ProjetLecteurMP3 \
  -Dsonar.organization=bleuenn-github -Dsonar.sources=. \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=7bf6b00bf632ec7a8f90fc7b9ed2f0aa551508b5
