dist: trusty
sudo: false
install: true

language: php
php:
  - 7.2

branches:
  only:
    master

addons:
  sonarcloud:
    organization: "bleuenn-github"
    token:
      secure: "30c2b84f460708d97c920681e5797748dfb3fde0"

jdk:
  - oraclejdk8

script:
  - cd model
  - phpunit DAOTest.php
  - cd ..
  - sonar-scanner