dist: trusty
sudo: true
language: php

git:
  depth: 1000

php:
  - 7.2

branches:
  only:
    master

install:
  - php composer.phar install --dev --no-interaction
  - sudo add-apt-repository ppa:chris-needham/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install audiowaveform -y
  - sudo apt-get install mediainfo -y

addons:
  sonarcloud:
    organization: "bleuenn-github"
    token:
      secure: "30c2b84f460708d97c920681e5797748dfb3fde0"

jdk:
  - oraclejdk8

script:
  - ./vendor/bin/phpunit
  - cd ./tests/javascript/
  - npm install
  - npm test
  - cd ../../
  - sonar-scanner
