dist: trusty
# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
- 5.4
- 5.5
- 5.6
- hhvm

# Commands to be run before your environment runs.
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.
script: phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm
  fast_finish: true

  addons:
    sonarcloud:
      organization: "Bleuenn_ProjetLecteurMP3"
      token:
        secure: SjwEcBuhQ+FvxuLTeaL/dS2VFi10VCAv9/rBsCK3mxWF3K2E4JWZLv+0mPtlQTivS6p4TakvKDyi2XnY9+NG41cokTDOIlfza5HCWlFSpWgLdHqmCI50OhEPVt0Mgf+a5eEEW8G8DqWbV3kNbmFm0GDyRvoPmETivFdWttFjJSnhsGxTRejzomK5GK+Rq4rO+UUPUpwIdrg4HsbSY7vR60wxTROWn78X44M+6g5/o0V2ra757j+3WBTPHNOOtM762dDXtBNZIn3BKF3Vw+0KIP6hL2bv9DgBpYLx8iDGZN8yyKh+3dZu7oXz42KCdHyykO1BNJYoJrTJuPTQeh4dQH4Ik1aoHoOz0cz22uJ5eIqXul1JmTpZxaHRW21KMiYSSYPqs/xbg9WtqsnRNtriYLJCkcGNyjEOcVQvwQvPocj4zVbCoWxRJzckMFrznP9JZ89rAqthouIEub8TmwnBq6HH10G+liHLlVb2beYQ2MdJaLUv+dVafdNMgMUmsRA+SVewJuzAsN1v7PWppdHYGsKW7MpGLhCITNjSYc0zbAaV1Q9JRoW5KPexmI0kT39dcw+Q2VtP+ovCtCKlgPS+peZ7R7uaLkYMbT0CEpxE2v8I9zPmqSB6idP54lVxBlGnnyEaEmLHEjaY4qPGnwN4kk3Z7YBYd3bLnyRuTlwfMLI=
  #script:
  # other script steps might be done before running the actual analysis
  #- sonar-scanner