dist: trusty
sudo: true
language: php

git:
  depth: 1000

php:
  - 7.2

branches:
  only:
    master

install:
  - php composer.phar install --dev --no-interaction
  - sudo add-apt-repository ppa:chris-needham/ppa
  - sudo apt-get update
  - sudo apt-get install audiowaveform
  - sudo apt-get install mediainfo
  - sudo apt-get ffmpeg

addons:
  sonarcloud:
    organization: "bleuenn-github"
    token:
      secure: "30c2b84f460708d97c920681e5797748dfb3fde0"

jdk:
  - oraclejdk8

script:
  - ./vendor/bin/phpunit
  - sonar-scanner

after_success:
  - travis_retry php vendor/bin/php-coveralls
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v

