language: php


git:
  depth: 1

php:
- 7.2

branches:
  only:
    master

before_install:
- travis_retry composer self-update
- composer install
- composer require --dev phpunit/phpunit ^6.5

script: phpunit /model/DAOTest.php